/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.pranavavva.javatactoe;

import java.awt.*;

public class App {
    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            GameFrame gameFrame = new GameFrame();
        });
    }
}
