/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.pranavavva.javatactoe;

import io.github.pranavavva.javatactoe.gui.GameFrame;

import javax.swing.*;
import java.awt.*;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        Board board = new Board();
        EventQueue.invokeLater(() -> new GameFrame(board));
    }
}
