/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.pranavavva.javatactoe;

import io.github.pranavavva.javatactoe.gui.GameFrame;

import java.awt.*;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Board board = new Board();
        EventQueue.invokeLater(() -> new GameFrame(board));
    }
}
